// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw8naOa22NxxAEAWDPPBXS31ThJrRBYFA',
    appId: '1:442546361632:android:385c838626734e5e05f345',
    messagingSenderId: '442546361632',
    projectId: 'disco-chat-bc2eb',
    storageBucket: 'disco-chat-bc2eb.firebasestorage.app',
  );

  

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALJD5rDMyQVr50IrmQW9QeKg5DPqV_X1M',
    appId: '1:442546361632:web:54d48e567eb811aa05f345',
    messagingSenderId: '442546361632',
    projectId: 'disco-chat-bc2eb',
    authDomain: 'disco-chat-bc2eb.firebaseapp.com',
    storageBucket: 'disco-chat-bc2eb.firebasestorage.app',
  );

}